### ISSUE TITLE
[BUG] ModlistUpdateChecker.ini not updated to show correct version of the list after updating/installing the 1.2.0 Anvil modlist.

### ISSUE THREAD

**Issue by gteachey** [Althro/Anvil#3]
**Upload your crash log**

If you've crashed, upload your crash log from `C:\Users\UserName\Documents\My Games\Skyrim Special Edition`. Reports of crashes that do not include a crash log will be **ignored and closed.**

**Required: Modlist.txt**
Default installed modlist. No added mods.

**Describe the bug**
anvil/mods/Modlist Update Checker\skse\plugins\ModlistUpdateChecker.ini after installing:

[General]
Name = ANVIL
Version = 1.1.0 <<<< MAKE ME 1.2.0 SEMPAI!!!
uNotificationDelay = 60
bAlwaysShowCurrentVersion = true
bDisable = false
bNoSaveSafeNotification = false
bExitIfNotLatest = false

[Wabbajack]
bUseWJ = true
MachineURL = Animonculory/ANVIL

[LoadOrderLibrary]
bUseLoadOrderLibrary = false
Endpoint = /v1/lists/anvil

[Log]
Debug = false

**To Reproduce**
Steps to reproduce the behaviour:

1. Download the modlist through Wabbajack
2. Run the modlist 0
3. Wait for Modlist Update Checker mod to check the version.
4. Get warning that it's 1.1.0 and needs an update.

**Expected behaviour**
1. Download the modlist through Wabbajack
2. Run the modlist 0
3. Wait for Modlist Update Checker mod to check the version.
4. See it retun version 1.2.0 with no warning

**Modlist version**
1.2.0

**Did you add any additional mods?**
No
***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***
I HAVE NOT :)

**Comment by Althro** [comment]
Fixed in 1.2.1
