### ISSUE TITLE
[BUG] Respawn Soulslike

### ISSUE THREAD

**Issue by zrvila** [Althro/Anvil#5]
**Upload your crash log**

Did not crash.

**Required: Modlist.txt**

Modlist is unmodified latest version of LoreRim from Wabbajack (installed yesterday)

**Describe the bug**
When I select the "respawn at Temple of Kynareth in Whiterun" option and I die, my character instead resets at the location where I died. A burnt corpse is generated when I died with some, but not all of my items. When I try to loot the corpse I can take the items but a script slowly pulls them from my inventory over about 10 seconds until everything is placed back in the corpse object. If I try to get one of the objects placed in the corpse object from another source it will also be removed from my inventory and placed on the corpse. There seems to be a long running script that keeps looking for those items.
This behavior also occurs when "respawn at nearest Hold" is selected.

This bug makes the modlist unplayable upon death.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to MCM and selected "respawn in nearest Hold" or "respawn at Temple of Kynareth"
2. Die
3. Try to loot burnt corpse of lost items (workaround, not intended behavior of mod setting at this point)
4. Try to obtain one of the items on the corpse from a different source (workaround, not intended behavior)

**Expected behaviour**
I respawn in the Temple of Kynareth with some items missing based on probability settings in the mod settings.

Or

I respawn in the nearest Hold Hall of the Dead.

**Screenshots**
None

**Modlist version**
Latest

**Did you add any additional mods?**
None added.

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
This is Anvil. Not LoreRim.
